// COPYRIGHT (C) HARRY CLARK 2023
//
// LENOVO THINKPAD P14S SSDT FOR HACKINTOSH
//
// THE FOLLOWING FILE IS AN EFFORT TO COMBINE THE TWO CON-CURRENT BATTERIES
// INTO ONE POWER SOURCE FOR THE LNV-5B10W51860 BATTERY

DefinitionBlock("", "SSDT", 2, "ACDT", "BAT0",0x00000000)
{
    
}